# This workflow will release the Eclipse repository on github when a new tag is pushed

name: Release on github

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: ${{ github.workspace }}/org.eclipse.xsmp.repository/target/org.eclipse.xsmp.repository-*.zip
      